(* SHAPE A implementation. Nobody reads this file; it exists to be compiled.
   Generated by sqlml from example/sql/users.sql. Do not edit. *)

[@@@warning "-69"]

type user_status =
  | Active
  | Banned

let user_status_to_string = function Active -> "active" | Banned -> "banned"

let user_status_of_row r i =
  match Sqlml.Row.string r i with
  | "active" -> Active
  | "banned" -> Banned
  | other -> raise (Sqlml.Row.Bad { column = i; expected = "user_status"; got = other })

module Get_user = struct
  type params = { id : string }

  type row =
    { id : string
    ; email : string
    ; display_name : string option
    ; status : user_status
    ; created_at : string
    }

  let name = "GetUser"

  let sql =
    "SELECT id, email, display_name, status, created_at\nFROM users\nWHERE id = $1"

  (* annotated because [row] also has an [id] field and is defined later *)
  let encode ({ id } : params) = [ Sqlml.Value.of_string id ]

  let decode r : row =
    { id = Sqlml.Row.string r 0
    ; email = Sqlml.Row.string r 1
    ; display_name = Sqlml.Row.(option string) r 2
    ; status = user_status_of_row r 3
    ; created_at = Sqlml.Row.string r 4
    }
end

let get_user conn ~id = Sqlml.fetch_one {Get_user} conn { Get_user.id }

module Search_users = struct
  type params =
    { organization_id : string
    ; email_pattern : string
    ; limit : int
    }

  type row =
    { id : string
    ; email : string
    ; created_at : string
    }

  let name = "SearchUsers"

  let sql =
    "SELECT id, email, created_at\n\
     FROM users\n\
     WHERE organization_id = $1\n\
    \  AND email ILIKE $2\n\
     ORDER BY created_at DESC\n\
     LIMIT $3"

  let encode ({ organization_id; email_pattern; limit } : params) =
    Sqlml.Value.[ of_string organization_id; of_string email_pattern; of_int limit ]

  let decode r : row =
    { id = Sqlml.Row.string r 0
    ; email = Sqlml.Row.string r 1
    ; created_at = Sqlml.Row.string r 2
    }
end

let search_users conn ~organization_id ~email_pattern ~limit =
  Sqlml.fetch_all {Search_users} conn { Search_users.organization_id; email_pattern; limit }

module Delete_user = struct
  type params = { id : string }

  let name = "DeleteUser"
  let sql = "DELETE FROM users WHERE id = $1"
  let encode ({ id } : params) = [ Sqlml.Value.of_string id ]
end

let delete_user conn ~id = Sqlml.exec {Delete_user} conn { Delete_user.id }
