(* Generated by sqlml from example/sql/users.sql -- do not edit.

   Nobody reads this file; it exists to be compiled. Every modular explicit in
   the project lives in the one-line wrappers at the bottom of each section. *)

[@@@warning "-69"]

type user_status =
  | Active
  | Banned

let user_status_to_string = function Active -> "active" | Banned -> "banned"

let user_status_of_row r i =
  match Sqlml.Row.string r i with
  | "active" -> Active
  | "banned" -> Banned
  | other -> raise (Sqlml.Row.Bad { column = i; expected = "user_status"; got = other })

let user_status_to_value s = Sqlml.Value.of_string (user_status_to_string s)

let _ = user_status_to_value

(* ---------- GetUser ---------- *)

type get_user_row =
  { id : Uuidm.t
  ; email : string
  ; display_name : string option
  ; status : user_status
  ; balance : Decimal.t
  ; created_at : Ptime.t
  }

module Get_user = struct
  type params = { id : Uuidm.t }
  type row = get_user_row

  let name = "GetUser"

  let sql =
    "SELECT id, email, display_name, status, balance, created_at\nFROM users\nWHERE id = $1"

  let encode ({ id } : params) = [ Sqlml.Value.of_uuid id ]

  let decode r : row =
    { id = Sqlml.Row.uuid r 0
    ; email = Sqlml.Row.string r 1
    ; display_name = Sqlml.Row.(option string) r 2
    ; status = user_status_of_row r 3
    ; balance = Sqlml.Row.decimal r 4
    ; created_at = Sqlml.Row.ptime r 5
    }

  let columns = 6

  let cardinality = Sqlml.Query.One
end

let get_user conn ~id = Sqlml.fetch_one (module Get_user) conn { Get_user.id }
let get_user_exn conn ~id = Sqlml.or_raise (get_user conn ~id)

(* ---------- SearchUsers ---------- *)

type search_users_row =
  { id : Uuidm.t
  ; email : string
  ; created_at : Ptime.t
  }

module Search_users = struct
  type params =
    { organization_id : Uuidm.t
    ; email_pattern : string
    ; limit : int
    }

  type row = search_users_row

  let name = "SearchUsers"

  let sql =
    "SELECT id, email, created_at\n\
     FROM users\n\
     WHERE organization_id = $1\n\
    \  AND email ILIKE $2\n\
     ORDER BY created_at DESC\n\
     LIMIT $3"

  let encode ({ organization_id; email_pattern; limit } : params) =
    Sqlml.Value.[ of_uuid organization_id; of_string email_pattern; of_int limit ]

  let decode r : row =
    { id = Sqlml.Row.uuid r 0
    ; email = Sqlml.Row.string r 1
    ; created_at = Sqlml.Row.ptime r 2
    }

  let columns = 3

  let cardinality = Sqlml.Query.Many
end

let search_users conn ~organization_id ~email_pattern ~limit =
  Sqlml.fetch_all (module Search_users) conn { Search_users.organization_id; email_pattern; limit }

let search_users_exn conn ~organization_id ~email_pattern ~limit =
  Sqlml.or_raise (search_users conn ~organization_id ~email_pattern ~limit)

(* ---------- CountPostsByUser ---------- *)

type count_posts_by_user_row =
  { email : string
  ; title : string option
  ; post_count : int
  }

module Count_posts_by_user = struct
  type params = unit
  type row = count_posts_by_user_row

  let name = "CountPostsByUser"

  let sql =
    "SELECT\n\
    \  u.email,\n\
    \  p.title,\n\
    \  coalesce(count(p.id), 0) AS \"post_count!\"\n\
     FROM users u\n\
     LEFT JOIN posts p ON p.author_id = u.id\n\
     GROUP BY u.email, p.title"

  let encode () = []

  let decode r : row =
    { email = Sqlml.Row.string r 0
    ; title = Sqlml.Row.(option string) r 1
    ; post_count = Sqlml.Row.int r 2
    }

  let columns = 3

  let cardinality = Sqlml.Query.Many
end

let count_posts_by_user conn = Sqlml.fetch_all (module Count_posts_by_user) conn ()
let count_posts_by_user_exn conn = Sqlml.or_raise (count_posts_by_user conn)

(* ---------- DeleteUser ---------- *)

module Delete_user = struct
  type params = { id : Uuidm.t }

  let name = "DeleteUser"
  let sql = "DELETE FROM users WHERE id = $1"
  let encode ({ id } : params) = [ Sqlml.Value.of_uuid id ]

  let cardinality = Sqlml.Query.Exec
end

let delete_user conn ~id = Sqlml.exec (module Delete_user) conn { Delete_user.id }
let delete_user_exn conn ~id = Sqlml.or_raise (delete_user conn ~id)
