(** Generated by sqlml from example/sql/users.sql -- do not edit.

    This file IS the user experience: it is the only thing anyone reads. Note
    what is absent -- no Caqti, no codecs, no [Sqlml.Query] plumbing a caller
    has to understand, and no modular explicits. The brace syntax appears only
    in db.ml, written by the generator.

    Shape C: row types live at the top level, so a single [open Db] gives you
    [u.email] anywhere; the query modules are exported too, so the generic
    runtime ([Sqlml.fetch_one {Db.Get_user}]) still works for tooling. *)

type user_status =
  | Active
  | Banned

val user_status_to_string : user_status -> string

(** {1 GetUser} *)

type get_user_row =
  { id : Uuidm.t
  ; email : string
  ; display_name : string option
  ; status : user_status
  ; balance : Decimal.t
  ; created_at : Ptime.t
  }

module Get_user : sig
  type params = { id : Uuidm.t }

  include Sqlml.Query.ONE with type params := params and type row = get_user_row
end

(** Fetch a single user by id.
    @raise Sqlml.Sql_error on connection, execution or decode failure. *)
val get_user : Sqlml.conn -> id:Uuidm.t -> get_user_row option

(** Non-raising {!get_user}. *)
val get_user_res : Sqlml.conn -> id:Uuidm.t -> (get_user_row option, Sqlml.Error.t) result

(** {1 SearchUsers} *)

type search_users_row =
  { id : Uuidm.t
  ; email : string
  ; created_at : Ptime.t
  }

module Search_users : sig
  type params =
    { organization_id : Uuidm.t
    ; email_pattern : string
    ; limit : int
    }

  include Sqlml.Query.MANY with type params := params and type row = search_users_row
end

(** Users in an organization whose email matches a pattern, newest first.
    @raise Sqlml.Sql_error on connection, execution or decode failure. *)
val search_users :
  Sqlml.conn -> organization_id:Uuidm.t -> email_pattern:string -> limit:int -> search_users_row list

(** Non-raising {!search_users}. *)
val search_users_res :
  Sqlml.conn ->
  organization_id:Uuidm.t ->
  email_pattern:string ->
  limit:int ->
  (search_users_row list, Sqlml.Error.t) result

(** {1 CountPostsByUser} *)

type count_posts_by_user_row =
  { email : string
  ; title : string option (* NOT NULL in the schema, nullable via LEFT JOIN *)
  ; post_count : int (* computed; pinned non-null by the "!" alias *)
  }

module Count_posts_by_user : sig
  type params = unit

  include Sqlml.Query.MANY with type params := params and type row = count_posts_by_user_row
end

(** @raise Sqlml.Sql_error on connection, execution or decode failure. *)
val count_posts_by_user : Sqlml.conn -> count_posts_by_user_row list

(** Non-raising {!count_posts_by_user}. *)
val count_posts_by_user_res : Sqlml.conn -> (count_posts_by_user_row list, Sqlml.Error.t) result

(** {1 DeleteUser} *)

module Delete_user : sig
  type params = { id : Uuidm.t }

  include Sqlml.Query.EXEC with type params := params
end

(** Returns the number of rows affected.
    @raise Sqlml.Sql_error on connection or execution failure. *)
val delete_user : Sqlml.conn -> id:Uuidm.t -> int

(** Non-raising {!delete_user}. *)
val delete_user_res : Sqlml.conn -> id:Uuidm.t -> (int, Sqlml.Error.t) result
