(** SHAPE A -- nested module per query.

    Generated by sqlml from example/sql/users.sql. Do not edit.

    This is the file that defines the user experience: it is the only thing
    anyone reads. Note what is absent -- no Caqti, no codecs, no modular
    explicits, no [Sqlml.Query] plumbing in any signature a caller must
    understand. The brace syntax exists only inside db.ml. *)

type user_status =
  | Active
  | Banned

val user_status_to_string : user_status -> string

(** {1 GetUser} *)

module Get_user : sig
  type params = { id : string }

  type row =
    { id : string
    ; email : string
    ; display_name : string option
    ; status : user_status
    ; created_at : string
    }

  (* Makes the module usable with the generic runtime:
       Sqlml.fetch_one {Db.Get_user} conn { id }
     Most callers want the wrapper below instead. *)
  include Sqlml.Query.ONE with type params := params and type row := row
end

(** Fetch a single user by id. *)
val get_user : Sqlml.conn -> id:string -> (Get_user.row option, Sqlml.Error.t) result

(** {1 SearchUsers} *)

module Search_users : sig
  type params =
    { organization_id : string
    ; email_pattern : string
    ; limit : int
    }

  type row =
    { id : string
    ; email : string
    ; created_at : string
    }

  include Sqlml.Query.MANY with type params := params and type row := row
end

(** Users in an organization whose email matches a pattern, newest first. *)
val search_users :
  Sqlml.conn ->
  organization_id:string ->
  email_pattern:string ->
  limit:int ->
  (Search_users.row list, Sqlml.Error.t) result

(** {1 DeleteUser} *)

module Delete_user : sig
  type params = { id : string }

  include Sqlml.Query.EXEC with type params := params
end

val delete_user : Sqlml.conn -> id:string -> (int, Sqlml.Error.t) result
