(** Generated by sqlml from example/sql/wide.sql -- do not edit.

    A realistic wide table: 25 columns, five queries. Demonstrates two things that only
    matter at width:

    - [GetUser] and [GetUserByEmail] both select every column of [users], so they share
      one {!users_row} rather than getting two identical-but- incompatible types. Detected
      from RowDescription's tableoid: every column belongs to the same table, and together
      they cover it.
    - Nullable parameters are optional arguments defaulting to [None], so wide inserts
      don't need a column of explicit [None]s. Any query with a nullable parameter takes a
      trailing [()]. *)

type user_status = Active | Invited | Suspended | Banned
type user_role = Owner | Admin | Member | Guest

(** {1 users}

    Shared model type: the full column set of the [users] table. Every query that selects
    exactly these columns returns this type, so helpers written against it work
    everywhere. *)

type users_row = {
  id : Uuidm.t;
  organization_id : Uuidm.t;
  email : string;
  email_verified_at : Ptime.t option;
  display_name : string option;
  given_name : string option;
  family_name : string option;
  avatar_url : string option;
  locale : string;
  timezone : string;
  status : user_status;
  role : user_role;
  balance : Decimal.t;
  credit_limit : Decimal.t option;
  login_count : int;
  failed_logins : int;
  last_login_at : Ptime.t option;
  last_seen_ip : string option;
  phone : string option;
  phone_verified : bool;
  marketing_opt_in : bool;
  metadata : string;
  created_at : Ptime.t;
  updated_at : Ptime.t;
  deleted_at : Ptime.t option;
}

(** {1 GetUser} *)

module Get_user : sig
  type params = { id : Uuidm.t }

  include Sqlml.Query.ONE with type params := params and type row = users_row
end

val get_user : Sqlml.conn -> id:Uuidm.t -> (users_row option, Sqlml.Error.t) result
val get_user_exn : Sqlml.conn -> id:Uuidm.t -> users_row option

(** {1 GetUserByEmail}

    Same {!users_row}, so anything written for {!get_user} works here too. *)

module Get_user_by_email : sig
  type params = { email : string }

  include Sqlml.Query.ONE with type params := params and type row = users_row
end

val get_user_by_email :
  Sqlml.conn -> email:string -> (users_row option, Sqlml.Error.t) result

val get_user_by_email_exn : Sqlml.conn -> email:string -> users_row option

(** {1 ListUserSummaries}

    A partial projection, so it keeps its own row type. *)

type list_user_summaries_row = {
  id : Uuidm.t;
  email : string;
  display_name : string option;
  status : user_status;
}

module List_user_summaries : sig
  type params = { organization_id : Uuidm.t; limit : int }

  include
    Sqlml.Query.MANY with type params := params and type row = list_user_summaries_row
end

val list_user_summaries :
  Sqlml.conn ->
  organization_id:Uuidm.t ->
  limit:int ->
  (list_user_summaries_row list, Sqlml.Error.t) result

val list_user_summaries_exn :
  Sqlml.conn -> organization_id:Uuidm.t -> limit:int -> list_user_summaries_row list

(** {1 CreateUser}

    Twelve parameters, four of them nullable. The nullable ones are optional and sort
    last, so the mandatory arguments stay in SQL order and the call ends with [()]. *)

module Create_user : sig
  type params = {
    organization_id : Uuidm.t;
    email : string;
    display_name : string option;
    given_name : string option;
    family_name : string option;
    locale : string;
    timezone : string;
    status : user_status;
    role : user_role;
    phone : string option;
    marketing_opt_in : bool;
    metadata : string;
  }

  include Sqlml.Query.EXEC with type params := params
end

val create_user :
  Sqlml.conn ->
  organization_id:Uuidm.t ->
  email:string ->
  locale:string ->
  timezone:string ->
  status:user_status ->
  role:user_role ->
  marketing_opt_in:bool ->
  metadata:string ->
  ?display_name:string ->
  ?given_name:string ->
  ?family_name:string ->
  ?phone:string ->
  unit ->
  (int, Sqlml.Error.t) result

val create_user_exn :
  Sqlml.conn ->
  organization_id:Uuidm.t ->
  email:string ->
  locale:string ->
  timezone:string ->
  status:user_status ->
  role:user_role ->
  marketing_opt_in:bool ->
  metadata:string ->
  ?display_name:string ->
  ?given_name:string ->
  ?family_name:string ->
  ?phone:string ->
  unit ->
  int
