(** Generated by sqlml from example/sql/wide.sql -- do not edit.

    A realistic wide table: 25 columns, five queries. This exists to show what
    the agreed API shape actually looks like at scale, where the pleasant
    four-column examples stop being representative. *)

type user_status =
  | Active
  | Invited
  | Suspended
  | Banned

type user_role =
  | Owner
  | Admin
  | Member
  | Guest

(** {1 GetUser} -- SELECT * FROM users WHERE id = :id *)

type get_user_row =
  { id : Uuidm.t
  ; organization_id : Uuidm.t
  ; email : string
  ; email_verified_at : Ptime.t option
  ; display_name : string option
  ; given_name : string option
  ; family_name : string option
  ; avatar_url : string option
  ; locale : string
  ; timezone : string
  ; status : user_status
  ; role : user_role
  ; balance : Decimal.t
  ; credit_limit : Decimal.t option
  ; login_count : int
  ; failed_logins : int
  ; last_login_at : Ptime.t option
  ; last_seen_ip : string option
  ; phone : string option
  ; phone_verified : bool
  ; marketing_opt_in : bool
  ; metadata : string
  ; created_at : Ptime.t
  ; updated_at : Ptime.t
  ; deleted_at : Ptime.t option
  }

module Get_user : sig
  type params = { id : Uuidm.t }

  include Sqlml.Query.ONE with type params := params and type row = get_user_row
end

val get_user : Sqlml.conn -> id:Uuidm.t -> (get_user_row option, Sqlml.Error.t) result
val get_user_exn : Sqlml.conn -> id:Uuidm.t -> get_user_row option

(** {1 GetUserByEmail} -- SELECT * FROM users WHERE email = :email

    Note: structurally identical to {!get_user_row}, but a distinct type. See
    the "shared row types" question in DESIGN.md. *)

type get_user_by_email_row =
  { id : Uuidm.t
  ; organization_id : Uuidm.t
  ; email : string
  ; email_verified_at : Ptime.t option
  ; display_name : string option
  ; given_name : string option
  ; family_name : string option
  ; avatar_url : string option
  ; locale : string
  ; timezone : string
  ; status : user_status
  ; role : user_role
  ; balance : Decimal.t
  ; credit_limit : Decimal.t option
  ; login_count : int
  ; failed_logins : int
  ; last_login_at : Ptime.t option
  ; last_seen_ip : string option
  ; phone : string option
  ; phone_verified : bool
  ; marketing_opt_in : bool
  ; metadata : string
  ; created_at : Ptime.t
  ; updated_at : Ptime.t
  ; deleted_at : Ptime.t option
  }

module Get_user_by_email : sig
  type params = { email : string }

  include Sqlml.Query.ONE with type params := params and type row = get_user_by_email_row
end

val get_user_by_email :
  Sqlml.conn -> email:string -> (get_user_by_email_row option, Sqlml.Error.t) result

val get_user_by_email_exn : Sqlml.conn -> email:string -> get_user_by_email_row option

(** {1 ListUserSummaries} -- a narrow projection over the same table *)

type list_user_summaries_row =
  { id : Uuidm.t
  ; email : string
  ; display_name : string option
  ; status : user_status
  }

module List_user_summaries : sig
  type params =
    { organization_id : Uuidm.t
    ; limit : int
    }

  include Sqlml.Query.MANY with type params := params and type row = list_user_summaries_row
end

val list_user_summaries :
  Sqlml.conn ->
  organization_id:Uuidm.t ->
  limit:int ->
  (list_user_summaries_row list, Sqlml.Error.t) result

val list_user_summaries_exn :
  Sqlml.conn -> organization_id:Uuidm.t -> limit:int -> list_user_summaries_row list

(** {1 CreateUser} -- twelve parameters. This is the labelled-argument stress
    case: the call site is unambiguous but tall. *)

module Create_user : sig
  type params =
    { organization_id : Uuidm.t
    ; email : string
    ; display_name : string option
    ; given_name : string option
    ; family_name : string option
    ; locale : string
    ; timezone : string
    ; status : user_status
    ; role : user_role
    ; phone : string option
    ; marketing_opt_in : bool
    ; metadata : string
    }

  include Sqlml.Query.EXEC with type params := params
end

val create_user :
  Sqlml.conn ->
  organization_id:Uuidm.t ->
  email:string ->
  display_name:string option ->
  given_name:string option ->
  family_name:string option ->
  locale:string ->
  timezone:string ->
  status:user_status ->
  role:user_role ->
  phone:string option ->
  marketing_opt_in:bool ->
  metadata:string ->
  (int, Sqlml.Error.t) result

val create_user_exn :
  Sqlml.conn ->
  organization_id:Uuidm.t ->
  email:string ->
  display_name:string option ->
  given_name:string option ->
  family_name:string option ->
  locale:string ->
  timezone:string ->
  status:user_status ->
  role:user_role ->
  phone:string option ->
  marketing_opt_in:bool ->
  metadata:string ->
  int
