(** The pipeline behind [sqlml generate] and [sqlml check]. Both run exactly the same
    steps — discover, parse, describe, emit, format — and differ only in what they do with
    the result; if check regenerated by a different route it could disagree with generate
    for reasons unrelated to schema drift. *)

type built = private { mli : string; ml : string; queries : int; files : int }

type drift =
  | Missing of string
  | Differs of { path : string; line : int; expected : string; actual : string }

val sql_files : string -> (string list, Diag.t) result
(** Every .sql under the directory, recursively, sorted; hidden directories and _build
    skipped. *)

val parse_all : string list -> (Parse.t list, Diag.t) result

val check_unique_names : Parse.t list -> (unit, Diag.t) result
(** Rejects two queries whose names snake_case to the same OCaml identifier; all queries
    generate into one module. *)

val first_difference : path:string -> expected:string -> actual:string -> drift option
(** The line-level diff a drift report points at. *)

val build : queries_dir:string -> conninfo:string -> (built, Diag.t) result

val describe :
  queries_dir:string -> conninfo:string -> (Describe.described list, Diag.t) result
(** The describe subcommand's pipeline: discover, parse, describe — no emit. *)

val write :
  out_dir:string -> module_name:string -> built -> (string * string, Diag.t) result
(** Writes [module_name].mli/.ml, formatted through the project's own ocamlformat; returns
    the two paths. Fails when ocamlformat is missing or mismatched — generate and check
    must format identically, or check would report phantom drift. *)

val check : out_dir:string -> module_name:string -> built -> (drift list, Diag.t) result
val string_of_drift : drift -> string
