(** The pipeline behind [sqlml generate] and [sqlml check]. Both run exactly the same
    steps — discover, parse, describe, emit, format — and differ only in what they do with
    the result; if check regenerated by a different route it could disagree with generate
    for reasons unrelated to schema drift. *)

type built = private { mli : string; ml : string; queries : int; files : int }

type drift =
  | Missing of string
  | Differs of { path : string; line : int; expected : string; actual : string }

val sql_files : string -> (string list, Diag.t) result
(** Every .sql under the directory, recursively, sorted; hidden directories and _build
    skipped. *)

val parse_all : string list -> (Parse.t list, Diag.t) result
val build : queries_dir:string -> conninfo:string -> (built, Diag.t) result

val write : out_dir:string -> module_name:string -> built -> string * string
(** Writes [module_name].mli/.ml, formatted through the project's own ocamlformat; returns
    the two paths. *)

val check : out_dir:string -> module_name:string -> built -> drift list
val string_of_drift : drift -> string
