(** The pipeline behind [sqlml generate] and [sqlml check].

    Both run exactly the same steps -- discover, parse, describe, emit -- and differ only
    in what they do with the result. That is deliberate: if check regenerated by a
    different route it could disagree with generate for reasons that have nothing to do
    with schema drift. *)

type built = { mli : string; ml : string; queries : int; files : int }

type drift =
  | Missing of string (* path *)
  | Differs of { path : string; line : int; expected : string; actual : string }

(* Every .sql file under [dir], recursively. Sorted so generated output is
   deterministic regardless of readdir order. Hidden directories and _build are
   skipped. *)
let sql_files dir =
  if not (Sys.file_exists dir) then Error (Printf.sprintf "no such directory: %s" dir)
  else if not (Sys.is_directory dir) then Error (Printf.sprintf "not a directory: %s" dir)
  else begin
    let acc = ref [] in
    let rec walk d =
      match Sys.readdir d with
      | exception Sys_error _ -> ()
      | entries ->
          Array.sort compare entries;
          Array.iter
            (fun e ->
              let path = Filename.concat d e in
              if String.length e > 0 && e.[0] = '.' then ()
              else if e = "_build" then ()
              else if Sys.is_directory path then walk path
              else if Filename.check_suffix e ".sql" then acc := path :: !acc)
            entries
    in
    walk dir;
    let fs = List.sort compare !acc in
    if fs = [] then Error (Printf.sprintf "no .sql files under %s" dir) else Ok fs
  end

let parse_all files =
  let rec go acc = function
    | [] -> Ok (List.concat (List.rev acc))
    | f :: tl -> (
        match Parse.of_file f with
        | Ok qs -> go (qs :: acc) tl
        | Error (e : Parse.error) ->
            Error (Printf.sprintf "%s:%d: %s" e.Parse.file e.Parse.line e.Parse.message))
  in
  go [] files

let ( let* ) = Result.bind

(* All queries land in one module regardless of which file they came from, so a
   name used twice would emit two modules of the same name and produce output
   that does not compile. Caught here, before the database round-trip, with both
   locations named. *)
let check_unique_names (queries : Parse.t list) =
  let seen = Hashtbl.create 16 in
  let rec go = function
    | [] -> Ok ()
    | (q : Parse.t) :: tl -> (
        match Hashtbl.find_opt seen q.Parse.name with
        | Some (f, l) ->
            Error
              (Printf.sprintf
                 "%s:%d: duplicate query name %S, already defined at %s:%d\n\
                 \  query names must be unique across every .sql file, because they all \
                  generate into one module"
                 q.Parse.file q.Parse.line q.Parse.name f l)
        | None ->
            Hashtbl.replace seen q.Parse.name (q.Parse.file, q.Parse.line);
            go tl)
  in
  go queries

let build ~queries_dir ~conninfo =
  let* files = sql_files queries_dir in
  let* queries = parse_all files in
  let* () = check_unique_names queries in
  let* conn = Describe.connect conninfo in
  let described =
    Describe.describe_all conn queries |> Result.map_error Describe.string_of_error
  in
  Pq.finish conn;
  let* described = described in
  let* config = Config.load queries_dir in
  let* mli, ml = Emit.generate ~config ~src:queries_dir described in
  Ok { mli; ml; queries = List.length described; files = List.length files }

(* Run generated source through ocamlformat, using whatever .ocamlformat applies
   to the output directory, so the result is already in the project's own style.

   This matters because `check` compares byte-for-byte. Without it, a user whose
   editor formats on save would see check fail forever on code they did not
   write. Formatting here means generate and check agree by construction.

   Silently returns the input unchanged when ocamlformat is not installed or
   rejects the file: formatting is a nicety, not a correctness requirement, and
   generate should not fail because a developer tool is missing. *)
let format ~dir ~ext contents =
  let base = Filename.concat dir ("sqlml_fmt_" ^ string_of_int (Unix.getpid ())) in
  let path = base ^ ext in
  let cleanup () = try Sys.remove path with _ -> () in
  match
    let oc = open_out_bin path in
    output_string oc contents;
    close_out oc;
    Sys.command
      (Printf.sprintf "ocamlformat --inplace %s 2>/dev/null" (Filename.quote path))
  with
  | 0 ->
      let ic = open_in_bin path in
      let n = in_channel_length ic in
      let out = really_input_string ic n in
      close_in ic;
      cleanup ();
      out
  | _ | (exception _) ->
      cleanup ();
      contents

let format_built ~out_dir b =
  let dir = if Sys.file_exists out_dir then out_dir else Filename.current_dir_name in
  { b with mli = format ~dir ~ext:".mli" b.mli; ml = format ~dir ~ext:".ml" b.ml }

let paths ~out_dir ~module_name =
  let base = Filename.concat out_dir module_name in
  (base ^ ".mli", base ^ ".ml")

let read_file path =
  if not (Sys.file_exists path) then None
  else
    let ic = open_in_bin path in
    let n = in_channel_length ic in
    let s = really_input_string ic n in
    close_in ic;
    Some s

let write_file path contents =
  let oc = open_out_bin path in
  output_string oc contents;
  close_out oc

let write ~out_dir ~module_name b =
  if not (Sys.file_exists out_dir) then Unix.mkdir out_dir 0o755;
  let b = format_built ~out_dir b in
  let mli_path, ml_path = paths ~out_dir ~module_name in
  write_file mli_path b.mli;
  write_file ml_path b.ml;
  (mli_path, ml_path)

(* First differing line, so the report points at something actionable rather
   than just saying the files differ. *)
let first_difference ~path ~expected ~actual =
  let e = String.split_on_char '\n' expected and a = String.split_on_char '\n' actual in
  let rec go i e a =
    match (e, a) with
    | [], [] -> None
    | eh :: et, ah :: at -> if eh = ah then go (i + 1) et at else Some (i, eh, ah)
    | eh :: _, [] -> Some (i, eh, "(end of file)")
    | [], ah :: _ -> Some (i, "(end of file)", ah)
  in
  match go 1 e a with
  | None -> None
  | Some (line, expected, actual) -> Some (Differs { path; line; expected; actual })

let check ~out_dir ~module_name b =
  (* the same formatting generate applies, so the comparison is like-for-like *)
  let b = format_built ~out_dir b in
  let mli_path, ml_path = paths ~out_dir ~module_name in
  List.filter_map
    (fun (path, expected) ->
      match read_file path with
      | None -> Some (Missing path)
      | Some actual ->
          if actual = expected then None else first_difference ~path ~expected ~actual)
    [ (mli_path, b.mli); (ml_path, b.ml) ]

let string_of_drift = function
  | Missing path -> Printf.sprintf "%s: missing -- has `sqlml generate` ever run?" path
  | Differs { path; line; expected; actual } ->
      Printf.sprintf "%s:%d: out of date\n  on disk:   %s\n  should be: %s" path line
        (String.trim actual) (String.trim expected)
