(** The pipeline behind [sqlml generate] and [sqlml check].

   Both run exactly the same steps -- discover, parse, describe, emit -- and
   differ only in what they do with the result. That is deliberate: if check
   regenerated by a different route it could disagree with generate for reasons
   that have nothing to do with schema drift. *)

type built =
  { mli : string
  ; ml : string
  ; queries : int
  ; files : int
  }

type drift =
  | Missing of string (* path *)
  | Differs of
      { path : string
      ; line : int
      ; expected : string
      ; actual : string
      }

(* Every .sql file under [dir], recursively. Sorted so generated output is
   deterministic regardless of readdir order. Hidden directories and _build are
   skipped. *)
let sql_files dir =
  if not (Sys.file_exists dir) then Error (Printf.sprintf "no such directory: %s" dir)
  else if not (Sys.is_directory dir) then Error (Printf.sprintf "not a directory: %s" dir)
  else begin
    let acc = ref [] in
    let rec walk d =
      match Sys.readdir d with
      | exception Sys_error _ -> ()
      | entries ->
        Array.sort compare entries;
        Array.iter
          (fun e ->
            let path = Filename.concat d e in
            if String.length e > 0 && e.[0] = '.' then ()
            else if e = "_build" then ()
            else if Sys.is_directory path then walk path
            else if Filename.check_suffix e ".sql" then acc := path :: !acc)
          entries
    in
    walk dir;
    let fs = List.sort compare !acc in
    if fs = [] then Error (Printf.sprintf "no .sql files under %s" dir) else Ok fs
  end

let parse_all files =
  let rec go acc = function
    | [] -> Ok (List.concat (List.rev acc))
    | f :: tl -> (
      match Parse.of_file f with
      | Ok qs -> go (qs :: acc) tl
      | Error (e : Parse.error) ->
        Error (Printf.sprintf "%s:%d: %s" e.Parse.file e.Parse.line e.Parse.message))
  in
  go [] files

let ( let* ) = Result.bind

let build ~queries_dir ~conninfo =
  let* files = sql_files queries_dir in
  let* queries = parse_all files in
  let* conn = Describe.connect conninfo in
  let described =
    Describe.describe_all conn queries |> Result.map_error Describe.string_of_error
  in
  Pq.finish conn;
  let* described = described in
  let* mli, ml = Emit.generate ~src:queries_dir described in
  Ok { mli; ml; queries = List.length described; files = List.length files }

let paths ~out_dir ~module_name =
  let base = Filename.concat out_dir module_name in
  (base ^ ".mli", base ^ ".ml")

let read_file path =
  if not (Sys.file_exists path) then None
  else (
    let ic = open_in_bin path in
    let n = in_channel_length ic in
    let s = really_input_string ic n in
    close_in ic;
    Some s)

let write_file path contents =
  let oc = open_out_bin path in
  output_string oc contents;
  close_out oc

let write ~out_dir ~module_name b =
  if not (Sys.file_exists out_dir) then Unix.mkdir out_dir 0o755;
  let mli_path, ml_path = paths ~out_dir ~module_name in
  write_file mli_path b.mli;
  write_file ml_path b.ml;
  (mli_path, ml_path)

(* First differing line, so the report points at something actionable rather
   than just saying the files differ. *)
let first_difference ~path ~expected ~actual =
  let e = String.split_on_char '\n' expected and a = String.split_on_char '\n' actual in
  let rec go i e a =
    match (e, a) with
    | [], [] -> None
    | eh :: et, ah :: at -> if eh = ah then go (i + 1) et at else Some (i, eh, ah)
    | eh :: _, [] -> Some (i, eh, "(end of file)")
    | [], ah :: _ -> Some (i, "(end of file)", ah)
  in
  match go 1 e a with
  | None -> None
  | Some (line, expected, actual) -> Some (Differs { path; line; expected; actual })

let check ~out_dir ~module_name b =
  let mli_path, ml_path = paths ~out_dir ~module_name in
  List.filter_map
    (fun (path, expected) ->
      match read_file path with
      | None -> Some (Missing path)
      | Some actual ->
        if actual = expected then None else first_difference ~path ~expected ~actual)
    [ (mli_path, b.mli); (ml_path, b.ml) ]

let string_of_drift = function
  | Missing path -> Printf.sprintf "%s: missing -- has `sqlml generate` ever run?" path
  | Differs { path; line; expected; actual } ->
    Printf.sprintf "%s:%d: out of date\n  on disk:   %s\n  should be: %s" path line
      (String.trim actual) (String.trim expected)
